spring:
    application:
        name: edge-server
        
server:
  port: 8765
  connection-timeout: 60000
  
eureka:  
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
      
ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000